spring:
  application:
    name: opensearchdemo
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

opensearch:
  host: localhost
  port: 9200
  scheme: https
  username: admin
  password: Random!Password1
  truststore:
    path: opensearch-truststore.jks
    password: changeit 